### ISSUE TITLE
Any updates

### ISSUE THREAD

**Issue by maierfelix** [PMArkive/ASH_Extractor#1]
@PMArkive Hey, did you manage to get this tool working? I found your forum post and I'm stuck at the same thing. I want to extract mii.arc.ash and pii.arc.ash from My Pokemon Ranch. On models-resource it seems someone actually managed to rip the models, I'm curious how he did that

**Comment by maierfelix** [comment]
I found [this](https://gist.github.com/maierfelix/a8d82aedcdbc0f1ab15b06b4a8c34abe) in the wii sdk, but still getting a segfault

**Comment by PMArkive** [comment]
It's one of those things that probably has a dumb/easy solution but nonetheless I've spent a lot of time on it without being able to fix it and now my job has taken a lot of my time way so I lost interest.

The code you posted is is likely a million times more helpful in figuring out why it crashes though.
Having a legible algorithm would make it easier to debug.

**Comment by maierfelix** [comment]
@PMArkive all right. Just to let you know, I got it working for the files which ASH tool can handle (new source [here](https://pastebin.com/D7M9YDWu)), but it still fails for the files in My Pokemon Ranch, though the first bytes returned are already correct.
